# remap prefix to Control + a
set -g prefix C-a
# bind 'C-a C-a' to type 'C-a'
bind C-a send-prefix
unbind C-b
set -g mouse on

# move status bar to the top
set-option -g status-position top

# set color for status bar
set-option -g status-style bg=colour235,fg=yellow,dim

# set window title list colors
set-window-option -g window-status-style fg=brightblue,bg=colour236,dim

# active window title colors
set-window-option -g window-status-current-style fg=brightred,bg=colour236,bright

# Getting interesting now, we use the vertical and horizontal
# symbols to split the screen
#bind | split-window -h
#bind - split-window -v

# use vim-like keys for splits and windows
bind-key v split-window -h
bind-key s split-window -v

# FZF
bind-key l display-popup -E "tmux ls | cut -d ':' -f1 | fzf --header='Switch session' | xargs -r tmux switch-client -t"
bind-key f display-popup -E "ls -d ~/(workspace|personal-workspace)/*/ | sed 's/\\/\$//' | fzf -m --header='Create new session' | awk -F/ '{print \$NF, \$0}' | xargs -n 2 -r sh -c 'tmux has-session -t \"=\$1\" 2>/dev/null || tmux new-session -ds \"\$1\" -c \"\$2\" && tmux switch-client -t \"$1\"' _"
bind-key k display-popup -E "tmux ls | cut -d ':' -f1 | fzf -m --header='Kill session' | xargs -L 1 -r tmux kill-session -t"

# moving between windows
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# switch windows alt+number
bind-key -n ^1 select-window -t 1

# kill session
bind-key Q kill-session
#resize-pane h resize-pane -L
#resize-pane j resize-pane -D
#resize-pane k resize-pane -U
#resize-pane l resize-pane -R

# reorder window indexes after deleting
set-option -g renumber-windows on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
